---
- name: Playbook - Install figlet
  hosts: labhosts
  gather_facts: yes   # default is yes

  tasks:
  - name: using apt to install figlet
    apt:
        name: figlet
        state: present
    become: yes

